const heros = [
  {
    id: 3,
    name: "Abin Sur",
    slug: "3-abin-sur",
    powerstats: {
      intelligence: 50,
      strength: 90,
      speed: 53,
      durability: 64,
      power: 99,
      combat: 65,
    },
    appearance: {
      gender: "Male",
      race: "Ungaran",
      height: ["6'1", "185 cm"],
      weight: ["200 lb", "90 kg"],
      eyeColor: "Blue",
      hairColor: "No Hair",
    },
    biography: {
      fullName: "",
      alterEgos: "No alter egos found.",
      aliases: ["Lagzia"],
      placeOfBirth: "Ungara",
      firstAppearance: "Showcase #22 (October, 1959)",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "Green Lantern, former history professor",
      base: "Oa",
    },
    connections: {
      groupAffiliation: "Green Lantern Corps, Black Lantern Corps",
      relatives:
        "Amon Sur (son), Arin Sur (sister), Thaal Sinestro (brother-in-law), Soranik Natu (niece)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/3-abin-sur.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/3-abin-sur.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/3-abin-sur.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/3-abin-sur.jpg",
    },
  },
  {
    id: 17,
    name: "Alfred Pennyworth",
    slug: "17-alfred-pennyworth",
    powerstats: {
      intelligence: 63,
      strength: 10,
      speed: 17,
      durability: 10,
      power: 7,
      combat: 55,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["160 lb", "72 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Alfred Thaddeus Crane Pennyworth",
      alterEgos: "No alter egos found.",
      aliases: ["Alfred Beagle"],
      placeOfBirth: "-",
      firstAppearance: "Batman #16 (April, 1943)",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation:
        "Butler; Caretaker, former Actor; Field Medic; Government Agent",
      base: "Wayne Manor; Batcave; Gotham City",
    },
    connections: {
      groupAffiliation: "Batman Family, Outsiders",
      relatives:
        "Jarvis Pennyworth (father, deceased), Wilfred Pennyworth (older brother), Daphne Pennyworth (niece); Bruce Wayne (Batman, legal ward)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/17-alfred-pennyworth.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/17-alfred-pennyworth.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/17-alfred-pennyworth.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/17-alfred-pennyworth.jpg",
    },
  },
  {
    id: 30,
    name: "Ant-Man",
    slug: "30-ant-man",
    powerstats: {
      intelligence: 100,
      strength: 18,
      speed: 23,
      durability: 28,
      power: 32,
      combat: 32,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'11", "211 cm"],
      weight: ["270 lb", "122 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Hank Pym",
      alterEgos: "Giant-Man, Goliath, Wasp II, Yellowjacket",
      aliases: [
        "Hank Pym",
        "Doctor Pym",
        "Ant-Man",
        "Goliath",
        "Yellowjacket",
        "Wasp",
        "Earth's Scientist Supreme",
      ],
      placeOfBirth: "Elmsford, New York",
      firstAppearance:
        "Tales to Astonish #27 (January, 1962) (as Hank Pym)  Tales to Astonish #35 (September, 1962) (as Ant-Man)",
      publisher: "Giant-Man",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, Biochemist, former manager of Avengers Compound",
      base: "Avengers Compound, Los Angeles; formerly Infinite Avengers Mansion; Captive aboard a Skrull ship; Avengers Mansion, New York City, New York",
    },
    connections: {
      groupAffiliation:
        "Avengers Academy, Secret Avengers; formerly Mighty Avengers, Avengers (founding member), Defenders, Future Iron Man's Team",
      relatives: "-",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/30-ant-man.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/30-ant-man.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/30-ant-man.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/30-ant-man.jpg",
    },
  },
  {
    id: 31,
    name: "Ant-Man II",
    slug: "31-ant-man-ii",
    powerstats: {
      intelligence: 75,
      strength: 18,
      speed: 17,
      durability: 40,
      power: 53,
      combat: 30,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'0", "183 cm"],
      weight: ["190 lb", "86 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Scott Lang",
      alterEgos: "No alter egos found.",
      aliases: ["Myrmidon", "Scott Edward Harris Lang"],
      placeOfBirth: "Coral Gables, Florida",
      firstAppearance: "Avengers Vol 1 #181 (March, 1979)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Electronics Technician,",
      base: "South Beach, Miami, Florida; formerly Farmingdale, Long Island, New York",
    },
    connections: {
      groupAffiliation:
        "Ant-Man Security Solutions; formerly Future Foundation (leader), Fantastic Four (leader), Defenders, Avengers, Heroes For Hire, Stark Industries",
      relatives:
        "Cassandra Eleanor Lang (daughter), Ruth (sister), Carl (brother-in-law), Peggy Rae (ex-wife)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/31-ant-man-ii.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/31-ant-man-ii.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/31-ant-man-ii.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/31-ant-man-ii.jpg",
    },
  },
  {
    id: 35,
    name: "Apocalypse",
    slug: "35-apocalypse",
    powerstats: {
      intelligence: 100,
      strength: 100,
      speed: 33,
      durability: 100,
      power: 100,
      combat: 60,
    },
    appearance: {
      gender: "Male",
      race: "Mutant",
      height: ["7'0", "213 cm"],
      weight: ["300 lb", "135 kg"],
      eyeColor: "Red",
      hairColor: "Black",
    },
    biography: {
      fullName: "En Sabah Nur",
      alterEgos: "No alter egos found.",
      aliases: [
        "The Eternal One",
        "the High Lord",
        "Set",
        "Huitxilopochti",
        "Sauru",
        "Kali-Ma",
      ],
      placeOfBirth: "Akkaba, Egypt",
      firstAppearance: "X-Factor #5 (June, 1986)",
      publisher: "Marvel Comics",
      alignment: "bad",
    },
    work: {
      occupation: "Student; formerly Conqueror; Scientist",
      base: "Celestial Ship, mobile",
    },
    connections: {
      groupAffiliation:
        "Clan Akkaba, employer of Apocalypse's Horsemen, Dark Riders, former employer of the Alliance of Evil, 198",
      relatives: "Baal of the Crimson Sands (adopted father, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/35-apocalypse.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/35-apocalypse.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/35-apocalypse.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/35-apocalypse.jpg",
    },
  },
  {
    id: 38,
    name: "Aquaman",
    slug: "38-aquaman",
    powerstats: {
      intelligence: 81,
      strength: 85,
      speed: 79,
      durability: 80,
      power: 100,
      combat: 80,
    },
    appearance: {
      gender: "Male",
      race: "Atlantean",
      height: ["6'1", "185 cm"],
      weight: ["325 lb", "146 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Orin",
      alterEgos: "No alter egos found.",
      aliases: [
        "Dweller in the Depths",
        "Swimmer",
        "Waterbearer",
        "Mental Man",
        "Aquaboy",
        "Water Wraith",
      ],
      placeOfBirth: "Atlantis",
      firstAppearance: "More Fun Comics #73 (November, 1941)",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "Protector of the Seas and Oceans, King of Poseidonis",
      base: "Atlantean Royal Palace; Poseidonis, Atlantis",
    },
    connections: {
      groupAffiliation:
        "Justice League, Aquaman Family, Atlantean Royal Family; formerly Black Lantern Corps, Justice League International, Justice League Detroit, U.N.",
      relatives:
        "Koryak (son), Arthur Curry, Jr. (son), A.J. (son), Orm Marius (half-brother), Debbie Perkins (half-sister), Drin (adopted brother), Atlanna (mother), Atlan (father), Atlena (aunt), Porm (adopted mother), Tom Curry (adopted father), Mera (wife), Hila (sister-in-law), Haumond (uncle), Kraken (uncle), Honsu (grandfather), Lorelei (grandmother), Manu (ancestor), Nala (ancestor), Fatima (ancestor), Kalunga (ancestor), Gana (ancestor), Fiona (ancestor), Regin (ancestor), Kordax (ancestor), Bazil (ancestor), Cora (ancestor), Illya (ancestor), Dardanus (ancestor), Alloroc (ancestor), Cole (ancestor), Narmea (ancestor), Orin (ancestor), Loma (ancestor), Shalako (ancestor), Thorvall (ancestor)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/38-aquaman.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/38-aquaman.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/38-aquaman.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/38-aquaman.jpg",
    },
  },
  {
    id: 60,
    name: "Bane",
    slug: "60-bane",
    powerstats: {
      intelligence: 88,
      strength: 38,
      speed: 23,
      durability: 56,
      power: 51,
      combat: 95,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'8", "203 cm"],
      weight: ["400 lb", "180 kg"],
      eyeColor: "-",
      hairColor: "-",
    },
    biography: {
      fullName: "",
      alterEgos: "No alter egos found.",
      aliases: ["-"],
      placeOfBirth: "-",
      firstAppearance: "Batman: Vengeance of Bane #1 (January, 1993)",
      publisher: "DC Comics",
      alignment: "bad",
    },
    work: {
      occupation: "-",
      base: "Santa Prisca",
    },
    connections: {
      groupAffiliation: "Suicide Squad, The Secret Society of Super Villains",
      relatives: "King Snake (father)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/60-bane.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/60-bane.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/60-bane.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/60-bane.jpg",
    },
  },
  {
    id: 63,
    name: "Batgirl",
    slug: "63-batgirl",
    powerstats: {
      intelligence: 88,
      strength: 11,
      speed: 33,
      durability: 40,
      power: 34,
      combat: 90,
    },
    appearance: {
      gender: "Female",
      race: "Human",
      height: ["5'7", "170 cm"],
      weight: ["126 lb", "57 kg"],
      eyeColor: "Green",
      hairColor: "Red",
    },
    biography: {
      fullName: "Barbara Gordon",
      alterEgos: "Oracle",
      aliases: ["Oracle", "Bluebelle"],
      placeOfBirth: "-",
      firstAppearance: "Detective Comics #359",
      publisher: "Oracle",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "Gotham City, formerly Metropolis, Platinum Flats",
    },
    connections: {
      groupAffiliation: "-",
      relatives:
        "James Gordon (father) ? Barbara Eileen (mother) ? James Gordon, Jr. (brother)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/63-batgirl.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/63-batgirl.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/63-batgirl.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/63-batgirl.jpg",
    },
  },
  {
    id: 66,
    name: "Batgirl IV",
    slug: "66-batgirl-iv",
    powerstats: {
      intelligence: 69,
      strength: 12,
      speed: 27,
      durability: 56,
      power: 46,
      combat: 100,
    },
    appearance: {
      gender: "Female",
      race: "Human",
      height: ["5'5", "165 cm"],
      weight: ["115 lb", "52 kg"],
      eyeColor: "Green",
      hairColor: "Black",
    },
    biography: {
      fullName: "Cassandra Cain",
      alterEgos: "No alter egos found.",
      aliases: ["Kasumi", "various mundane persona,"],
      placeOfBirth: "League of Assassins (exact base is unknown)",
      firstAppearance: "Batman: Legends of the Dark Knight #120",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "Gotham City; Bl?dhaven; Tibet; New York City",
    },
    connections: {
      groupAffiliation:
        "Titans East, League of Assassins, Batman Family, Justice League Elite, Young Justice",
      relatives:
        "David Cain (father), Lady Shiva (mother), Carolyn (aunt, deceased), Annalea (sibling, deceased), 'The Mad Dog' (sibling)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/66-batgirl-iv.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/66-batgirl-iv.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/66-batgirl-iv.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/66-batgirl-iv.jpg",
    },
  },
  {
    id: 68,
    name: "Batgirl VI",
    slug: "68-batgirl-vi",
    powerstats: {
      intelligence: 75,
      strength: 10,
      speed: 23,
      durability: 28,
      power: 22,
      combat: 80,
    },
    appearance: {
      gender: "Female",
      race: null,
      height: ["5'6", "168 cm"],
      weight: ["135 lb", "61 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Stephanie Brown",
      alterEgos: "Spoiler",
      aliases: ["Steph", "Robin", "Marion Todd", "Spoiler"],
      placeOfBirth: "-",
      firstAppearance:
        "Detective Comics #647. As Batgirl in Batgirl (Volume 3) #1. (2009)",
      publisher: "Spoiler",
      alignment: "good",
    },
    work: {
      occupation: "College student at Gotham University",
      base: "Gotham Heights, Gotham City",
    },
    connections: {
      groupAffiliation:
        "The Batman Family, formerly the Birds of Prey, Tim Drake (on-and-off boyfriend)",
      relatives:
        "Arthur Brown (The Cluemaster, father), Crystal Brown (mother), unnamed daughter (given up for adoption)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/68-batgirl-vi.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/68-batgirl-vi.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/68-batgirl-vi.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/68-batgirl-vi.jpg",
    },
  },
  {
    id: 69,
    name: "Batman",
    slug: "69-batman",
    powerstats: {
      intelligence: 81,
      strength: 40,
      speed: 29,
      durability: 55,
      power: 63,
      combat: 90,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["170 lb", "77 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Terry McGinnis",
      alterEgos: "No alter egos found.",
      aliases: [
        "Batman II",
        "The Tomorrow Knight",
        "The second Dark Knight",
        "The Dark Knight of Tomorrow",
        "Batman Beyond",
      ],
      placeOfBirth: "Gotham City, 25th Century",
      firstAppearance: "Batman Beyond #1",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "21st Century Gotham City",
    },
    connections: {
      groupAffiliation: "Batman Family, Justice League Unlimited",
      relatives:
        "Bruce Wayne (biological father), Warren McGinnis (father, deceased), Mary McGinnis (mother), Matt McGinnis (brother)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/69-batman.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/69-batman.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/69-batman.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/69-batman.jpg",
    },
  },
  {
    id: 70,
    name: "Batman",
    slug: "70-batman",
    powerstats: {
      intelligence: 100,
      strength: 26,
      speed: 27,
      durability: 50,
      power: 47,
      combat: 100,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'2", "188 cm"],
      weight: ["210 lb", "95 kg"],
      eyeColor: "blue",
      hairColor: "black",
    },
    biography: {
      fullName: "Bruce Wayne",
      alterEgos: "No alter egos found.",
      aliases: ["Insider", "Matches Malone"],
      placeOfBirth: "Crest Hill, Bristol Township; Gotham County",
      firstAppearance: "Detective Comics #27",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "Businessman",
      base: "Batcave, Stately Wayne Manor, Gotham City; Hall of Justice, Justice League Watchtower",
    },
    connections: {
      groupAffiliation:
        "Batman Family, Batman Incorporated, Justice League, Outsiders, Wayne Enterprises, Club of Heroes, formerly White Lantern Corps, Sinestro Corps",
      relatives:
        "Damian Wayne (son), Dick Grayson (adopted son), Tim Drake (adopted son), Jason Todd (adopted son), Cassandra Cain (adopted ward)\nMartha Wayne (mother, deceased), Thomas Wayne (father, deceased), Alfred Pennyworth (former guardian), Roderick Kane (grandfather, deceased), Elizabeth Kane (grandmother, deceased), Nathan Kane (uncle, deceased), Simon Hurt (ancestor), Wayne Family",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/70-batman.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/70-batman.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/70-batman.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/70-batman.jpg",
    },
  },
  {
    id: 106,
    name: "Black Panther",
    slug: "106-black-panther",
    powerstats: {
      intelligence: 88,
      strength: 16,
      speed: 30,
      durability: 60,
      power: 41,
      combat: 100,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'0", "183 cm"],
      weight: ["200 lb", "90 kg"],
      eyeColor: "Brown",
      hairColor: "Black",
    },
    biography: {
      fullName: "T'Challa",
      alterEgos: "No alter egos found.",
      aliases: [
        "Mr. Okonkwo",
        "The Man Without Fear",
        "Luke Charles",
        "Black Leopard",
        "the Client",
        "Coal Tiger",
        "has impersonated Daredevil and others on occasion",
      ],
      placeOfBirth: "Wakanda, Africa",
      firstAppearance: "Fantastic Four Vol. 1 #52 (1966)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation:
        "King and Chieftain of Wakanda, scientist; former school teacher",
      base: "Wakanda, Mobile",
    },
    connections: {
      groupAffiliation:
        "Formerly Fantastic Four, Secret Avengers, Avengers, Pendragons, Queen's Vengeance, former Fantastic Force financier",
      relatives:
        "Bashenga (paternal ancestor, deceased), Azzuri the Wise (paternal grandfather, deceased), Nanali (paternal grandmother, deceased), Chanda (paternal grandfather, presumably deceased), T?Chaka (father, deceased), S'Yan (uncle, deceased), N?Yami (mother, deceased), Ramonda (stepmother), Hunter (adopted brother), Jakarra (half-brother), Shuri (sister), Ororo Munroe (wife), Joshua Itobo, Ishanta, Zuni, M'Koni, T'Shan (cousins), Wheeler (cousin by marriage, deceased), Billy Wheeler (1st cousin once removed)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/106-black-panther.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/106-black-panther.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/106-black-panther.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/106-black-panther.jpg",
    },
  },
  {
    id: 107,
    name: "Black Widow",
    slug: "107-black-widow",
    powerstats: {
      intelligence: 75,
      strength: 13,
      speed: 33,
      durability: 30,
      power: 36,
      combat: 100,
    },
    appearance: {
      gender: "Female",
      race: "Human",
      height: ["5'7", "170 cm"],
      weight: ["131 lb", "59 kg"],
      eyeColor: "Green",
      hairColor: "Auburn",
    },
    biography: {
      fullName: "Natasha Romanoff",
      alterEgos: "No alter egos found.",
      aliases: [
        "Yelena Belova",
        "Natasha Romanoff",
        "Natasha",
        "Tasha",
        "Madame Natasha",
        "Nancy Rushman",
        "Laura Matthers",
        "Nadine Roman",
        '"Oktober"',
        "Black Pearl",
        "Ebon Flame",
      ],
      placeOfBirth: "-",
      firstAppearance: "Tales of Suspense #52",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, Intelligence agent, former ballerina",
      base: "Mobile",
    },
    connections: {
      groupAffiliation:
        'Secret Avengers; formerly Thunderbolts (as Yelena Belova), Nick Fury, Mighty Avengers, S.H.I.E.L.D., Avengers, Champions of Los Angeles, Lady Liberators, KGB, "Marvel Knights", partner of Daredevil, Hawkeye, Boris Turgenov, Logan',
      relatives:
        "Unnamed parents (presumed deceased); Alexi Shostakov (Red Guardian, estranged husband); Vindiktor (alleged brother, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/107-black-widow.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/107-black-widow.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/107-black-widow.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/107-black-widow.jpg",
    },
  },
  {
    id: 112,
    name: "Blade",
    slug: "112-blade",
    powerstats: {
      intelligence: 63,
      strength: 28,
      speed: 38,
      durability: 50,
      power: 40,
      combat: 90,
    },
    appearance: {
      gender: "Male",
      race: "Vampire",
      height: ["6'2", "188 cm"],
      weight: ["215 lb", "97 kg"],
      eyeColor: "Brown",
      hairColor: "Black",
    },
    biography: {
      fullName: "Eric Brooks",
      alterEgos: "No alter egos found.",
      aliases: ["Switchblade", "Frank Blade", "Daywalker"],
      placeOfBirth: "Soho, London,England",
      firstAppearance: "Tomb of Dracula Vol. 1 #10 (1973)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Vampire hunter, former private investigator.",
      base: "Mobile",
    },
    connections: {
      groupAffiliation:
        "Formerly Noah van Helsing's vampire hunters, Nightstalkers, Midnight Sons, the Nine, Quincy Harker's vampire hunters, Ogun Strong's vampire hunters, Bloodshadows gang",
      relatives: "Tara Brooks (mother)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/112-blade.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/112-blade.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/112-blade.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/112-blade.jpg",
    },
  },
  {
    id: 141,
    name: "Bullseye",
    slug: "141-bullseye",
    powerstats: {
      intelligence: 50,
      strength: 11,
      speed: 25,
      durability: 70,
      power: 20,
      combat: 70,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'0", "183 cm"],
      weight: ["200 lb", "90 kg"],
      eyeColor: "blue",
      hairColor: "blond",
    },
    biography: {
      fullName: "Lester",
      alterEgos: "No alter egos found.",
      aliases: [
        "Benjamin Poindexter",
        "Daredevil",
        "Punisher",
        "Bullseye",
        "Hawkeye",
        "pitcher",
      ],
      placeOfBirth: "-",
      firstAppearance: "Daredevil #131 (March, 1976)",
      publisher: "Marvel Comics",
      alignment: "bad",
    },
    work: {
      occupation: "Assassin, professional criminal, former mercenary",
      base: "Formerly Avengers Tower; Thunderbolts Mountain",
    },
    connections: {
      groupAffiliation:
        "Formerly Dark Avengers, Thunderbolts, employee of Kingpin, Purple Man, Eric Slaughter, Mysterio; formerly US Army",
      relatives: "Kingmaker (father)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/141-bullseye.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/141-bullseye.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/141-bullseye.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/141-bullseye.jpg",
    },
  },
  {
    id: 149,
    name: "Captain America",
    slug: "149-captain-america",
    powerstats: {
      intelligence: 69,
      strength: 19,
      speed: 38,
      durability: 55,
      power: 60,
      combat: 100,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'2", "188 cm"],
      weight: ["240 lb", "108 kg"],
      eyeColor: "blue",
      hairColor: "blond",
    },
    biography: {
      fullName: "Steve Rogers",
      alterEgos: "No alter egos found.",
      aliases: ["Nomad", "The Captain"],
      placeOfBirth: "Manhattan, New York City, New York",
      firstAppearance: "Captain America Comics #1 (March 1941)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation:
        "Adventurer, federal official, intelligence operative; former soldier, Hydra agent, liaison between S.H.I.E.L.D. and the Avengers, police officer, teacher, sparring partner.",
      base: "New York City",
    },
    connections: {
      groupAffiliation:
        "Secret Avengers (Black OPS Unit Formerly,The Avengers, Secret Avengers (Civil War), New Avengers, formerly The Invaders, Secret Defenders The Redeemers; formerly partner of Bucky, Golden Girl, Rick Jones, Falcon, Demolition-Man and Nomad (Jack Monroe)",
      relatives:
        "Joseph (father, deceased), Sara (mother, deceased), Ian Zola (Nomad) (adopted son)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/149-captain-america.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/149-captain-america.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/149-captain-america.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/149-captain-america.jpg",
    },
  },
  {
    id: 151,
    name: "Captain Britain",
    slug: "151-captain-britain",
    powerstats: {
      intelligence: 75,
      strength: 77,
      speed: 50,
      durability: 60,
      power: 31,
      combat: 80,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'6", "198 cm"],
      weight: ["257 lb", "116 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Brian Braddock",
      alterEgos: "No alter egos found.",
      aliases: [
        "Britannic",
        "Black Bishop",
        "Jungle Man",
        "King of Otherworld",
        "Merlinson",
      ],
      placeOfBirth: "Braddock Manor, England",
      firstAppearance: "Captain Britain #1 (October, 1976)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, formerly King of Otherworld, scientist",
      base: "Lighthouse, Earth Orbit; Starlight Citadel, Otherworld; formerly Braddock Manor; Braddock Lighthouse, England; New York City (during exchange trip, specifically Peter Parker's Manhattan apartment); flat near Thames University, London",
    },
    connections: {
      groupAffiliation:
        "Braddock Academy, Captain Britain Corps, MI-13; formerly Excalibur, Hellfire Club (London Branch), Secret Avengers, Court of Otherworld, Knights of Pendragon's ally, Future Iron Man's Team",
      relatives:
        "John Braddock (ancestor, possibly grandfather), James Braddock, Sr. (father, deceased), Lady Elizabeth Braddock (mother, deceased), James Braddock, Jr. (brother), Elizabeth Braddock (twin sister), Meggan (wife), William Puceanu (father-in-law)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/151-captain-britain.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/151-captain-britain.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/151-captain-britain.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/151-captain-britain.jpg",
    },
  },
  {
    id: 157,
    name: "Captain Marvel",
    slug: "157-captain-marvel",
    powerstats: {
      intelligence: 84,
      strength: 88,
      speed: 71,
      durability: 95,
      power: 100,
      combat: 90,
    },
    appearance: {
      gender: "Female",
      race: "Human-Kree",
      height: ["5'11", "180 cm"],
      weight: ["165 lb", "74 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Carol Danvers",
      alterEgos: "Binary, Warbird",
      aliases: [
        "Ace",
        "Binary",
        "Lady Marvel",
        "Warbird",
        "others used during her espionage career",
      ],
      placeOfBirth: "Boston, Massachusetts",
      firstAppearance: "Ms. Marvel #1",
      publisher: "Binary",
      alignment: "good",
    },
    work: {
      occupation:
        "Former National Aeronautics and Space Administration security Chief, former magazine editor, former freelance writer, former military intelligence officer.",
      base: "Avengers Mansion",
    },
    connections: {
      groupAffiliation:
        "currently Avengers, former companion to the X-Men (as Carol Danvers), former member of the Starjammers (as Binary), Former Avenger (as Ms. Marvel)",
      relatives:
        'Marie Danvers (mother), Joseph Danvers, Sr. (father), Joseph Danvers, Jr. (brother), Steve Danvers (brother, deceased), Marcus Immortus (Danvers) ("son", deceased)',
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/157-captain-marvel.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/157-captain-marvel.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/157-captain-marvel.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/157-captain-marvel.jpg",
    },
  },
  {
    id: 162,
    name: "Carnage",
    slug: "162-carnage",
    powerstats: {
      intelligence: 63,
      strength: 63,
      speed: 70,
      durability: 84,
      power: 88,
      combat: 90,
    },
    appearance: {
      gender: "Male",
      race: "Symbiote",
      height: ["6'1", "185 cm"],
      weight: ["190 lb", "86 kg"],
      eyeColor: "Green",
      hairColor: "Red",
    },
    biography: {
      fullName: "Cletus Kasady",
      alterEgos: "No alter egos found.",
      aliases: ["Mass Carnage", "999th"],
      placeOfBirth: "-",
      firstAppearance: "Amazing Spider-Man #344 (February, 1991)",
      publisher: "Marvel Comics",
      alignment: "bad",
    },
    work: {
      occupation: "-",
      base: "New York City",
    },
    connections: {
      groupAffiliation:
        "Maximum Carnage: (Carrion, Shriek, Demogoblin, Doppelganger)",
      relatives:
        'Venom ("father"); Shriek ("wife"); Hybrid, Lasher, Phage, Riot ("brothers"); Agony, Scream ("sisters"); Carrion, Demogoblin, Doppelganger, Toxin ("sons"); Scorn ("Daughter")',
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/162-carnage.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/162-carnage.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/162-carnage.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/162-carnage.jpg",
    },
  },
  {
    id: 165,
    name: "Catwoman",
    slug: "165-catwoman",
    powerstats: {
      intelligence: 69,
      strength: 11,
      speed: 33,
      durability: 28,
      power: 27,
      combat: 85,
    },
    appearance: {
      gender: "Female",
      race: "Human",
      height: ["5'9", "175 cm"],
      weight: ["135 lb", "61 kg"],
      eyeColor: "Green",
      hairColor: "Black",
    },
    biography: {
      fullName: "Selina Kyle",
      alterEgos: "No alter egos found.",
      aliases: [
        "The Cat",
        "Irena Dubrovna",
        "Elva Barr",
        "Sadie Kelowski",
        "Madame Moderne",
        "Marguerite Tone",
      ],
      placeOfBirth: "Gotham City",
      firstAppearance: "Detective Comics #569",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "Thief",
      base: "Gotham City",
    },
    connections: {
      groupAffiliation:
        "Batman Family, Outsiders; formerly Birds of Prey, Injustice League, Secret Society of Super-Villains",
      relatives:
        "Brian Kyle (father, deceased), Maria Kyle (mother, deceased), Maggie Kyle (sister), Helena Kyle (daughter)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/165-catwoman.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/165-catwoman.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/165-catwoman.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/165-catwoman.jpg",
    },
  },
  {
    id: 185,
    name: "Colossus",
    slug: "185-colossus",
    powerstats: {
      intelligence: 63,
      strength: 83,
      speed: 33,
      durability: 100,
      power: 45,
      combat: 80,
    },
    appearance: {
      gender: "Male",
      race: "Mutant",
      height: ["7'5", "226 cm"],
      weight: ["500 lb", "225 kg"],
      eyeColor: "Silver",
      hairColor: "Black",
    },
    biography: {
      fullName: "Piotr Nikolaievitch Rasputin",
      alterEgos: "No alter egos found.",
      aliases: ["Pete", "Peter Nicholas", "The Proletarian", "Little Brother"],
      placeOfBirth:
        "Ust-Ordynski Collective, near Lake Baikal, Siberia, Russia",
      firstAppearance: "Giant-Size X-Men #1 (May, 1975)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "(current) Adventurer, student, (former) Artist",
      base: "(current) Professor Charles Xavier's Institute for Higher Learning, Salem Center, Westchester County, New York (former) Muir Isle, Scotland,; a loft in Soho, Manhattan, Ust-Ordynski Collective, Lake Baikal, Siberia, U.S.S.R., X-Men Headquarters in Austra",
    },
    connections: {
      groupAffiliation: "X-Men; formerly Excalibur, Acolytes, Defender",
      relatives:
        "Grigory Efimovich Rasputin (great-grandfather, deceased), Elena (great-grandmother, deceased), Ivan Rasputin (great-grand uncle, deceased), Grigory Rasputin (grandfather, deceased), Nikolai Rasputin (father, deceased), Alexandra Rasputina (mother, deceased), Vladimir Rasputin (uncle, deceased), unidentified aunt & uncle (deceased), Illyana Nikolievna Rasputina (Magik, sister, deceased), Mikhail Rasputin (brother), Peter Jr. (son), Larissa Mishchenko (cousin, deceased), Konstantin (cousin, deceased), Klara (cousin, deceased), Dimitriy (cousin, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/185-colossus.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/185-colossus.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/185-colossus.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/185-colossus.jpg",
    },
  },
  {
    id: 194,
    name: "Cyborg",
    slug: "194-cyborg",
    powerstats: {
      intelligence: 75,
      strength: 53,
      speed: 42,
      durability: 85,
      power: 71,
      combat: 64,
    },
    appearance: {
      gender: "Male",
      race: "Cyborg",
      height: ["6'6", "198 cm"],
      weight: ["385 lb", "173 kg"],
      eyeColor: "Brown",
      hairColor: "Black",
    },
    biography: {
      fullName: "Victor Stone",
      alterEgos: "No alter egos found.",
      aliases: ["Cyberion Technis", "Omegadrome", "Planet Cyberion"],
      placeOfBirth: "New York City, New York",
      firstAppearance: "DC Comics Presents #26 (October, 1980)",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, Teen Titan",
      base: "San Francisco",
    },
    connections: {
      groupAffiliation:
        "Justice League; formerly Teen Titans, Titans, Titans East, New Teen Titans",
      relatives:
        "Silas Stone (father), Elinore Stone (mother), Tucker Stone (grandfather), Maude Stone (grandmother)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/194-cyborg.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/194-cyborg.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/194-cyborg.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/194-cyborg.jpg",
    },
  },
  {
    id: 196,
    name: "Cyclops",
    slug: "196-cyclops",
    powerstats: {
      intelligence: 75,
      strength: 10,
      speed: 23,
      durability: 42,
      power: 76,
      combat: 80,
    },
    appearance: {
      gender: "Male",
      race: "Mutant",
      height: ["6'3", "191 cm"],
      weight: ["195 lb", "88 kg"],
      eyeColor: "Brown",
      hairColor: "Brown",
    },
    biography: {
      fullName: "Scott Summers",
      alterEgos: "No alter egos found.",
      aliases: [
        "Scotty",
        "Cyke",
        "Slim",
        "Fearless Leader",
        "One-Eye",
        "Erik the Red",
        "Slym Dayspring",
        "Mutate 007",
        "Apocalypse",
      ],
      placeOfBirth: "Anchorage, Alaska",
      firstAppearance: "X-Men #1 (September, 1963)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation:
        "Leader of mutant race, adventurer, headmaster, former student, radio announcer",
      base: "Xavier Institute, Salem Center, Westchester County, New York",
    },
    connections: {
      groupAffiliation:
        "X-Men (leader, founding member); formerly X-Force (founder); Corsairs (squad leader); The Twelve; X-Factor/X-Terminators (founding member); 198",
      relatives:
        "Oscar Summers (adoptive paternal distant ancestor, deceased); Daniel Summers (paternal distant ancestor, deceased); Amanda Mueller (Black Womb) (paternal distant ancestor); unnamed great-grandfather, deceased; Gloria Dayne (Fontanelle) (paternal distant ancestor); Philip Summers (paternal grandfather); Deborah Summers (paternal grandmother); Christopher Summers (Corsair) (father, deceased); Katherine Ann Summers (mother, deceased); Jack Winters (Jack O'Diamonds) (former foster father); Alexander Summers (Havok) (brother); Gabriel Summers (Vulcan) (brother, deceased); Madelyne Pryor-Summers (Red Queen) (first wife/second wife's clone, deceased); Jean Grey-Summers (Phoenix) (second wife, deceased); Nathan Summers (Cable) (son, deceased); Gailyn Bailey (niece, deceased); Joseph Bailey (nephew, deceased); Adam Neramani (X-Treme) (nephew, alleged half-brother); Hope Summers (adoptive granddaughter); Stryfe (son's clone); Summers and Grey Family Tree (more relatives)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/196-cyclops.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/196-cyclops.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/196-cyclops.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/196-cyclops.jpg",
    },
  },
  {
    id: 201,
    name: "Daredevil",
    slug: "201-daredevil",
    powerstats: {
      intelligence: 75,
      strength: 13,
      speed: 25,
      durability: 35,
      power: 61,
      combat: 100,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'0", "183 cm"],
      weight: ["200 lb", "90 kg"],
      eyeColor: "Blue",
      hairColor: "Red",
    },
    biography: {
      fullName: "Matt Murdock",
      alterEgos: "No alter egos found.",
      aliases: [
        "Matt",
        "Jack Batlin",
        "Kingpin of Crime",
        "Laurent LeVasseur",
        'Michael "Mike" Murdock',
        "Scarlet Swashbuckler",
        "Nameless One",
        "Kingpin of Hell's Kitchen",
        "The Man Without Fear",
        "The Guardian Devil",
        "DD",
        "Red",
        "Hornhead",
        "Cooper Peyton",
        "Captain Universe",
      ],
      placeOfBirth: "New York City, New York",
      firstAppearance: "Daredevil #1 (April, 1964)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, vigilante, Attorney at Law",
      base: "Hell's Kitchen, New York, New York, Shadowland (formerly)",
    },
    connections: {
      groupAffiliation:
        "none; Formerly: partner of Black Widow (Natasha Romanoff), Defenders, S.H.I.E.L.D., Marvel Knights, Secret Avengers (Civil War), Hand leader.",
      relatives:
        'Jonathan "Battling Jack" Murdock (Father, deceased), Maggie Murdock (aka Sister Maggie, Mother), Milla Donovan (ex-wife)',
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/201-daredevil.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/201-daredevil.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/201-daredevil.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/201-daredevil.jpg",
    },
  },
  {
    id: 414,
    name: "Loki",
    slug: "414-loki",
    powerstats: {
      intelligence: 88,
      strength: 63,
      speed: 46,
      durability: 85,
      power: 100,
      combat: 60,
    },
    appearance: {
      gender: "Male",
      race: "Asgardian",
      height: ["6'4", "193 cm"],
      weight: ["525 lb", "236 kg"],
      eyeColor: "Green",
      hairColor: "Black",
    },
    biography: {
      fullName: "Loki Laufeyson",
      alterEgos: "No alter egos found.",
      aliases: [
        "God of Mischief",
        "Gem-Keeper",
        "Walter Lawson",
        "Lester",
        "Loren Olsen",
        "Tyfon",
        "Father Williams",
        "Willie",
        "Tso Zhung; has also impersonated hundreds of others.",
      ],
      placeOfBirth: "Jotunheim, Asgard",
      firstAppearance: "Journey into Mystery Vol. 1 #85",
      publisher: "Marvel Comics",
      alignment: "bad",
    },
    work: {
      occupation: "God of evil; former god of mischief and madness",
      base: "Asgard",
    },
    connections: {
      groupAffiliation:
        'Asgardians, Karnilla, Enchantress, Skurge the Executioner, Cobra, Mister Hyde, Absorbing Man, Igron, Tyr, Lorelei, Hela, Ulik, Frost Giants, Storm Giants (former), Dormammu, "Acts of Vengeance" prime movers (Dr. Doom, Magneto, Red Skull, Mandari',
      relatives:
        "Laufey (father, deceased), Farbauti (mother, deceased), Sigyn (wife, deceased), Odin (foster father, deceased), Frigga (foster mother, deceased), Thor, Vidar (foster brothers, deceased), Hela,Fenris (Wolf), Jordmungand (Midgard Serpent) (children, deceased), Arkin (cousin, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/414-loki.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/414-loki.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/414-loki.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/414-loki.jpg",
    },
  },
  {
    id: 416,
    name: "Luke Cage",
    slug: "416-luke-cage",
    powerstats: {
      intelligence: 50,
      strength: 63,
      speed: 29,
      durability: 95,
      power: 44,
      combat: 70,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'6", "198 cm"],
      weight: ["425 lb", "191 kg"],
      eyeColor: "Brown",
      hairColor: "Black",
    },
    biography: {
      fullName: "Luke Cage",
      alterEgos: "Power Man",
      aliases: [
        "Carl Lucas",
        "Power Man",
        "Mark Lucas",
        "Hero for Hire",
        "Ace of Spades",
      ],
      placeOfBirth: "Harlem, New York City",
      firstAppearance: "Hero for Hire #1 (1972)",
      publisher: "Power Man",
      alignment: "good",
    },
    work: {
      occupation:
        "Adventurer, bar owner, bodyguard, mercenary; formerly theater owner, private investigator, various odd jobs",
      base: "-",
    },
    connections: {
      groupAffiliation:
        "Underground Avengers (formerly Daredevil's Unnamed Super-Hero Team), Secret Defenders, Heroes for Hire, Nightwing Restorations, Fantastic Four, Defenders, Bloods",
      relatives:
        "Jessica Jones (wife), James Leonard Lucas (father), Esther (mother, deceased), James Jr. (Coldfire, brother), unnamed daughter",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/416-luke-cage.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/416-luke-cage.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/416-luke-cage.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/416-luke-cage.jpg",
    },
  },
  {
    id: 549,
    name: "Red Robin",
    slug: "549-red-robin",
    powerstats: {
      intelligence: 81,
      strength: 11,
      speed: 27,
      durability: 32,
      power: 29,
      combat: 80,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'5", "165 cm"],
      weight: ["125 lb", "56 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Tim Drake",
      alterEgos: "Robin III",
      aliases: [
        "Alvin Draper",
        "Batman",
        "Robin",
        "Timothy Wayne",
        "Time Drake",
      ],
      placeOfBirth: "Gotham City",
      firstAppearance: "Batman #436 (August, 1989)",
      publisher: "Robin III",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "Gotham City; Titans Tower, San Francisco",
    },
    connections: {
      groupAffiliation:
        "Teen Titans, Batman Family, Batman Inc., Wayne Enterprises; formerly Young Justice",
      relatives:
        "Jack Drake (father, deceased), Janet Drake (mother, deceased), Dana Winters Drake (step-mother, status unknown), Bruce Wayne (adoptive father), Damian Wayne (adoptive brother), Dick Grayson (adoptive brother), Jason Todd (adoptive brother), Cassandra Cain (adoptive sister)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/549-red-robin.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/549-red-robin.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/549-red-robin.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/549-red-robin.jpg",
    },
  },
  {
    id: 558,
    name: "Riddler",
    slug: "558-riddler",
    powerstats: {
      intelligence: 100,
      strength: 10,
      speed: 12,
      durability: 14,
      power: 10,
      combat: 14,
    },
    appearance: {
      gender: "Male",
      race: null,
      height: ["-", "0 cm"],
      weight: ["- lb", "0 kg"],
      eyeColor: "-",
      hairColor: "-",
    },
    biography: {
      fullName: "Edward Nigma",
      alterEgos: "No alter egos found.",
      aliases: ["E. Nigma", "Edward E. Nigma"],
      placeOfBirth: "-",
      firstAppearance: "Detective Comics #140 (1948)",
      publisher: "DC Comics",
      alignment: "bad",
    },
    work: {
      occupation: "-",
      base: "-",
    },
    connections: {
      groupAffiliation: "-",
      relatives: "-",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/558-riddler.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/558-riddler.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/558-riddler.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/558-riddler.jpg",
    },
  },
  {
    id: 561,
    name: "Robin",
    slug: "561-robin",
    powerstats: {
      intelligence: 88,
      strength: 11,
      speed: 27,
      durability: 28,
      power: 32,
      combat: 85,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["175 lb", "79 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Dick Grayson",
      alterEgos: "Batman II, Nightwing",
      aliases: ["Renegade", "The Target", "Freddie Dinardo"],
      placeOfBirth: "-",
      firstAppearance: "Detective Comics #38 (April, 1940)",
      publisher: "Batman II",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "Wayne Tower, Gotham City; formerly the Batcave;  formerly Bl?dhaven;  formerly New York City",
    },
    connections: {
      groupAffiliation:
        "Batman Family, Batman Incorporated, Justice League; formerly Teen Titans, Outsiders, Bludhaven Police Department, Secret Society of Super-Villains",
      relatives:
        "John Grayson (father), Mary Grayson (mother), Bruce Wayne (adoptive father), Damian Wayne (adoptive brother), Jason Todd (adoptive brother), Tim Drake (adoptive brother), Cassandra Cain (adoptive sister)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/561-robin.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/561-robin.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/561-robin.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/561-robin.jpg",
    },
  },
  {
    id: 562,
    name: "Robin II",
    slug: "562-robin-ii",
    powerstats: {
      intelligence: 75,
      strength: 11,
      speed: 27,
      durability: 28,
      power: 28,
      combat: 85,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["6'0", "183 cm"],
      weight: ["225 lb", "101 kg"],
      eyeColor: "Blue",
      hairColor: "Red",
    },
    biography: {
      fullName: "Jason Todd",
      alterEgos: "Red Hood",
      aliases: [
        "Red Hood",
        "Red Robin",
        "Batman",
        "Nightwing",
        "Wingman",
        "Jaybird",
        "Arkham Knight",
      ],
      placeOfBirth: "-",
      firstAppearance: "Detective Comics #524",
      publisher: "Red Hood",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "-",
    },
    connections: {
      groupAffiliation: "Batman Family, Teen Titans, Challengers from Beyond",
      relatives:
        "Willis Todd (father), Sheila Haywood (mother), Catherine Todd (step-mother), Bruce Wayne (Batman, adoptive father), Damian Wayne (Robin V, adoptive brother), Dick Grayson (Robin I, adoptive brother), Timothy Drake (Robin III, adoptive brother), Cassandra Cain (Batgirl IV, adoptive sister)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/562-robin-ii.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/562-robin-ii.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/562-robin-ii.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/562-robin-ii.jpg",
    },
  },
  {
    id: 563,
    name: "Robin III",
    slug: "563-robin-iii",
    powerstats: {
      intelligence: 81,
      strength: 11,
      speed: 27,
      durability: 28,
      power: 29,
      combat: 85,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'5", "165 cm"],
      weight: ["125 lb", "56 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Tim Drake",
      alterEgos: "Red Robin",
      aliases: ["Alvin Draper", "Batman", "Robin", "Timothy Wayne"],
      placeOfBirth: "-",
      firstAppearance: "Batman #436 (August, 1989)",
      publisher: "Red Robin",
      alignment: "good",
    },
    work: {
      occupation: "High School Student",
      base: "Gotham City; Titans Tower, San Francisco",
    },
    connections: {
      groupAffiliation:
        "Teen Titans, Batman Family, Batman Inc., Wayne Enterprises; formerly Young Justice",
      relatives:
        "Jack Drake (father, deceased), Janet Drake (mother, deceased), Dana Winters Drake (step-mother, status unknown), Bruce Wayne (Batman, adoptive father), Damian Wayne (Robin V, adoptive brother), Dick Grayson (Robin I, adoptive brother), Jason Todd (Robin II, adoptive brother), Cassandra Cain (Batgirl IV, adoptive sister)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/563-robin-iii.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/563-robin-iii.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/563-robin-iii.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/563-robin-iii.jpg",
    },
  },
  {
    id: 564,
    name: "Robin V",
    slug: "564-robin-v",
    powerstats: {
      intelligence: 69,
      strength: 8,
      speed: 33,
      durability: 16,
      power: 29,
      combat: 65,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["4'6", "137 cm"],
      weight: ["84 lb", "38 kg"],
      eyeColor: "Blue",
      hairColor: "Black",
    },
    biography: {
      fullName: "Damian Wayne",
      alterEgos: "No alter egos found.",
      aliases: ["Batman", "Damian al Ghul", "Ibn al Xu'ffasch", "Redbird"],
      placeOfBirth: "-",
      firstAppearance: "Batman: Son of the Demon",
      publisher: "DC Comics",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "Gotham City",
    },
    connections: {
      groupAffiliation:
        "Batman Family, Batman Inc., Wayne Enterprises; formerly Teen Titans, League of Assassins",
      relatives:
        "Talia al Ghul (mother),\nBruce Wayne (Batman, father),\nRa's Al Ghul (maternal grandfather),\nMelisande (maternal grandmother),\nThomas Wayne (paternal grandfather),\nMartha Wayne (paternal grandmother),\nSensei (great-grandfather),\nSimon Hurt (ancestor),\nNyssa Raatko (aunt, deceased),\nDusan al Ghul (White Ghost, uncle, deceased),\nRichard Grayson (Nightwing, adoptive brother),\nTim Drake (Red Robin, adoptive brother),\nCassandra Cain (Batgirl IV, adoptive sister),\nJason Todd (Red Hood, adoptive brother), \nPatrick Wayne (great-grandfather, deceased); \nCharles Wayne (great-great-grandfather, deceased);\nConstance Wayne (great-great-grandmother, deceased); \nAlan Wayne (ancestor, deceased); \nSolomon Wayne (ancestor, deceased); \nDarius Wayne (ancestor, deceased); \nJoshua Wayne (ancestor, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/564-robin-v.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/564-robin-v.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/564-robin-v.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/564-robin-v.jpg",
    },
  },
  {
    id: 567,
    name: "Rogue",
    slug: "567-rogue",
    powerstats: {
      intelligence: 75,
      strength: 10,
      speed: 12,
      durability: 28,
      power: 80,
      combat: 80,
    },
    appearance: {
      gender: "Female",
      race: null,
      height: ["5'8", "173 cm"],
      weight: ["120 lb", "54 kg"],
      eyeColor: "Green",
      hairColor: "Brown / White",
    },
    biography: {
      fullName: "Anna Marie",
      alterEgos: "No alter egos found.",
      aliases: [
        "Anna Raven",
        "Doctor Kellogg",
        "Mutate 9602",
        "Irene Adler",
        "Miss Smith",
      ],
      placeOfBirth: "Caldecott County, Mississippi",
      firstAppearance: "Avengers Annual #10 (1981)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer, former mechanic, waitress, terrorist",
      base: "-",
    },
    connections: {
      groupAffiliation:
        "X-Men, formerly X-Treme Sanctions Executive, X-Treme X-Men, Brotherhood of Evil Mutants",
      relatives:
        "Owen (father), Priscilla (mother), Carrie (aunt), Raven Darkh?lme (Mystique, foster mother), Kurt Wagner (Nightcrawler, foster brother), Graydon Creed (foster brother, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/567-rogue.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/567-rogue.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/567-rogue.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/567-rogue.jpg",
    },
  },

  {
    id: 579,
    name: "Scarlet Witch",
    slug: "579-scarlet-witch",
    powerstats: {
      intelligence: 100,
      strength: 10,
      speed: 29,
      durability: 70,
      power: 100,
      combat: 80,
    },
    appearance: {
      gender: "Female",
      race: "Mutant",
      height: ["5'7", "170 cm"],
      weight: ["132 lb", "59 kg"],
      eyeColor: "Blue",
      hairColor: "Brown",
    },
    biography: {
      fullName: "Wanda Maximoff",
      alterEgos: "No alter egos found.",
      aliases: [
        "Wanda Frank",
        "Wanda Magnus",
        "Ana Maximoff",
        "Gypsy Witch",
        "The Witch",
      ],
      placeOfBirth: "Wundagore Mountain, Transia",
      firstAppearance: "Uncanny X-Men #4 (March, 1964)",
      publisher: "Marvel Comics",
      alignment: "bad",
    },
    work: {
      occupation: "Adventurer; formerly witchcraft tutor, housewife, terrorist",
      base: "Mobile; formerly The Works; Avengers Compound, California; Avengers Mansion, New York",
    },
    connections: {
      groupAffiliation:
        "None, Formerly Avengers, Avengers West Coast, Force Works, Queen's Vengeance, Secret Defenders, Lady Liberators, Brotherhood of Evil Mutants",
      relatives:
        "Pietro (Quicksilver, twin brother), Magnus (Magneto, father), Magda Lehnsherr (mother, deceased), Anya (half-sister, deceased), Lorna Dane (Polaris, half-sister), Vision (estranged husband), Django Maximoff (foster father, deceased), Marya Maximoff (foster mother, deceased), Crystal (sister-in-law), Luna (niece), Tommy & Billy (reincarnated sons), Talia Wagner (Nocturne, alternate reality daughter)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/579-scarlet-witch.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/579-scarlet-witch.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/579-scarlet-witch.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/579-scarlet-witch.jpg",
    },
  },
  {
    id: 587,
    name: "Shang-Chi",
    slug: "587-shang-chi",
    powerstats: {
      intelligence: 63,
      strength: 12,
      speed: 30,
      durability: 50,
      power: 29,
      combat: 100,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["175 lb", "79 kg"],
      eyeColor: "Brown",
      hairColor: "Black",
    },
    biography: {
      fullName: "Shang-Chi",
      alterEgos: "No alter egos found.",
      aliases: [
        "The Master of Kung Fu; The Rising and Advancing of the Spirit; Chinaman (by Jack Tarr)",
      ],
      placeOfBirth: "-",
      firstAppearance: "Special Marvel Edition #15 (December, 1973)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "-",
      base: "-",
    },
    connections: {
      groupAffiliation:
        'MI-5, MI-6, "Marvel Knights", Heroes For Hire, Freelance Restorations, Si-Fan, Secret Avengers',
      relatives:
        "Fu Manchu, father; unnamed mother; Fah Lo Suee, (half-sister); Whispering Shadow (half-brother, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/587-shang-chi.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/587-shang-chi.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/587-shang-chi.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/587-shang-chi.jpg",
    },
  },

  {
    id: 620,
    name: "Spider-Man",
    slug: "620-spider-man",
    powerstats: {
      intelligence: 90,
      strength: 55,
      speed: 67,
      durability: 75,
      power: 74,
      combat: 85,
    },
    appearance: {
      gender: "Male",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["165 lb", "74 kg"],
      eyeColor: "Hazel",
      hairColor: "Brown",
    },
    biography: {
      fullName: "Peter Parker",
      alterEgos: "No alter egos found.",
      aliases: [
        "Spiderman",
        "Bag-Man",
        "Black Marvel",
        "Captain Universe",
        "Dusk",
        "Green Hood",
        "Hornet",
        "Mad Dog 336",
        "Peter Palmer",
        "Prodigy",
        "Ricochet",
        "Scarlet Spider",
        "Spider-Boy",
        "Spider-Hulk",
        "Spider-Morphosis",
      ],
      placeOfBirth: "New York, New York",
      firstAppearance: "Amazing Fantasy #15",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Freelance photographer, teacher",
      base: "New York, New York",
    },
    connections: {
      groupAffiliation:
        "Member of the Avengers, formerly member of Outlaws, alternate Fantastic Four",
      relatives:
        "Richard Parker (father, deceased), Mary Parker(mother, deceased), Benjamin Parker (uncle, deceased), May Parker (aunt), Mary Jane Watson-Parker (wife), May Parker (daughter, allegedly deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/620-spider-man.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/620-spider-man.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/620-spider-man.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/620-spider-man.jpg",
    },
  },
  {
    id: 623,
    name: "Spider-Woman",
    slug: "623-spider-woman",
    powerstats: {
      intelligence: 56,
      strength: 42,
      speed: 42,
      durability: 60,
      power: 68,
      combat: 70,
    },
    appearance: {
      gender: "Female",
      race: "Human",
      height: ["5'10", "178 cm"],
      weight: ["130 lb", "59 kg"],
      eyeColor: "Green",
      hairColor: "Black",
    },
    biography: {
      fullName: "Jessica Drew",
      alterEgos: "No alter egos found.",
      aliases: [
        "Arachne",
        "Ariadne Hyde",
        "Dark Angel",
        "Dark Angel of San Francisco",
      ],
      placeOfBirth: "London, England",
      firstAppearance: "Marvel Spotlight #32 (February, 1977)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation:
        "Form agent of HYDRA, former bounty hunter, private investigator, adventurer",
      base: "-",
    },
    connections: {
      groupAffiliation: "Former agent of HYDRA",
      relatives: "Jonathan (father, deceased), Merriem (mother, deceased)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/623-spider-woman.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/623-spider-woman.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/623-spider-woman.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/623-spider-woman.jpg",
    },
  },
  {
    id: 630,
    name: "Star-Lord",
    slug: "630-star-lord",
    powerstats: {
      intelligence: 69,
      strength: 20,
      speed: 33,
      durability: 50,
      power: 25,
      combat: 70,
    },
    appearance: {
      gender: "Male",
      race: "Human-Spartoi",
      height: ["6'2", "188 cm"],
      weight: ["175 lb", "79 kg"],
      eyeColor: "Blue",
      hairColor: "Blond",
    },
    biography: {
      fullName: "Peter Jason Quill",
      alterEgos: "No alter egos found.",
      aliases: ["Starlord"],
      placeOfBirth: "-",
      firstAppearance: "Marvel Preview #4 (January, 1976)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer; Royal Prince of Spartax",
      base: "C.I.T.T.; formerly Kree space; Hala, Daedalus 5",
    },
    connections: {
      groupAffiliation:
        "Guardians of the Galaxy (leader); formerly unnamed commando team, United Front, Imperial Guard, partner of Ship, NASA",
      relatives:
        "Eson (grandfather, deceased), Gareth (great-uncle, deceased), Jason of Sparta (father), Meredith Quill (mother, deceased), Victoria (half-sister), Kip Holm (adopted brother), Sandy (adopted sister in-law), Alain (adopted niece), Rhys, Robyn (adopted nephews), Kitty Pryde (fiance), Unnamed former Symbiote",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/630-star-lord.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/630-star-lord.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/630-star-lord.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/630-star-lord.jpg",
    },
  },

  {
    id: 638,
    name: "Storm",
    slug: "638-storm",
    powerstats: {
      intelligence: 75,
      strength: 10,
      speed: 47,
      durability: 30,
      power: 88,
      combat: 75,
    },
    appearance: {
      gender: "Female",
      race: "Mutant",
      height: ["5'11", "180 cm"],
      weight: ["127 lb", "57 kg"],
      eyeColor: "Blue",
      hairColor: "White",
    },
    biography: {
      fullName: "Ororo Munroe",
      alterEgos: "No alter egos found.",
      aliases: [
        "Ororo Iqadi T'Challa",
        "Queen Ororo",
        "Ororo Komo Wakandas,White Queen",
        "Weather Witch",
        "Windrider",
        "Goddess",
        "Mistress of the Elements",
        "Princess of N'Dare",
        "High Priestess Windrider",
        "Goddess",
        "Mistress of the Elements",
        "Princess of N'Dare",
        "High Priestess",
      ],
      placeOfBirth: "New York, New York",
      firstAppearance: "Giant-Size X-Men #1 (May, 1975)",
      publisher: "Marvel Comics",
      alignment: "good",
    },
    work: {
      occupation: "Adventurer",
      base: "Xavier Institute, Salem Center, Westchester County, New York State",
    },
    connections: {
      groupAffiliation:
        "X-Men (Jean Grey School member, leader); formerly X-Force (Strike Team); Murder Circus (brainwashed), Extinction Team, Avengers[3], Fantastic Four, X.S.E., X-Treme X-Men, Tokyo Arena, The Twelve, Seven Brides of Set, Hellfire Club (Inner Circle), Morlocks",
      relatives:
        "Ayesha of Balobedu (ancestor), Ashake of Egypt (ancestor), Ashake of Mero? (ancestor), unnamed ancestor, Harriet Munroe (paternal grandmother), unnamed paternal grandfather, unnamed maternal grandmother, David Munroe (father, deceased), N'Dar? Munroe (mother, deceased), Ainet (unofficial foster mother), Achmed El Gib?r (unofficial foster father), Colonel Shetani (maternal uncle), unnamed paternal aunt (deceased), David Munroe, Jr. (cousin), Munroe Family (relatives), Black Panther (T'Challa) (ex-husband, marriage annulled)",
    },
    images: {
      xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/638-storm.jpg",
      sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/638-storm.jpg",
      md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/638-storm.jpg",
      lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/638-storm.jpg",
    },
  },
];
export default heros;
